# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: c
sudo: required
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

r_github_packages:
  - rstudio/rmarkdown
  - jimhester/covr

env:
  global:
    - WARNINGS_ARE_ERRORS=1
    - R_BUILD_ARGS=--no-manual
    - R_CHECK_ARGS=--no-manual --as-cran

install:
  - ./travis-tool.sh install_deps

script: ./travis-tool.sh run_tests

on_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - Rscript -e 'covr::codecov()'